### ISSUE TITLE
i18n files do not work in DT 1.10

### ISSUE THREAD

**Issue by SantjagoCorkez** [DataTables/Plugins#131]
DT 1.10 does not recognize translation files that use hungarian notation, at least in case the whole table is initialized without fallback mode. There could be an option to make copies of i18n files under 1.10 directory for those who use DT in native mode or create a duplicate for each of rows in i18n files with key names that do not use hungarian notation.

**Comment by rhyudek1** [comment]
Hi, I have the same issue, I could fix it by removing comments of .lang file. Please update repositories without comments.

**Comment by delijati** [comment]
There is still that issue and no info about removing the comments

**Comment by xvonabur** [comment]
Hello! I've spent an hour trying to apply a language file. Please, remove comments in the repo, so people can use .lang files out the box.

**Comment by bahjaat** [comment]
+1 for leaving out the comments. It's very misleading.

**Comment by Art4** [comment]
I'm also just stumbled across this problem. We want to host all files on our own servers. +1 for leaving out the comments and renaming the ending `.lang` to `.json`

**Comment by gmormorromrom** [comment]
I am working in symfony and an error in line 1 of the language file has appeared. I have removed all comments and now all is well

**Comment by DataTables** [comment]
As noted above - that files stored here are not valid JSON and shouldn't be loaded directly. Get the actual JSON files from our CDN.

**Comment by xvonabur** [comment]
@DataTables Unfortunately, not everyone can use your CDN. Some projects requires to host all assets on in-house servers and not use third-party CDNs for security reasons. It's a shame that issue was created 4 years ago and nothing changed since then.

**Comment by DataTables** [comment]
That's cool. So download the file and host it locally :).

I agree that it would be nice to change the structure of this repo, but its not something I've prioritised yet, instead choosing to focus on other aspects of DataTables and its extensions. If someone would like to take the work on, then they are welcome to.
