### ISSUE TITLE
Accent neutralise does not work with text into HTML tags

### ISSUE THREAD

**Issue by eusonlito** [DataTables/Plugins#132]
Using this plugin https://github.com/DataTables/Plugins/blob/master/filtering/type-based/accent-neutralise.js with this HTML code:

``` html
<tr>
    <td><a href="http://github.com">Máis Github</a></td>
    <td>Sí</td>
</tr>
```

the text into `<a></a>` tag is not fixed to search without accent, but the second column is.

A `console.log(data)` after `jQuery.fn.DataTable.ext.type.search.string = function ( data ) {` only show strings `Sí`.

Regards.

**Comment by eusonlito** [comment]
Hi! any news about this issue? Thanks!

**Comment by DataTables** [comment]
No sorry - I've been working on other things. I'll try to get to this as soon as I can, but as noted above, can't say when that will be.

**Comment by eusonlito** [comment]
Thanks, no problem. I will fork it o test some solutions :+1:

**Comment by eusonlito** [comment]
I'm trying to replace the default datatables search function but I can't.

This is my code explained (I'm using multiple tables):

```javascript
$.extend($.fn.dataTable.defaults, {
    dom: "<'row'<'col-sm-8'f><'col-sm-4'l>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'i><'col-sm-7'p>>",
    bDestroy: true,
    bPaginate: true,
    bSort: true,
    bInfo: true,
    bAutoWidth: false,
    bProcessing: true,
    aaSorting: [],
    pageLength: 15,
    aLengthMenu: [[15, 30, 50, 100, -1], [15, 30, 50, 100, 'Todo']],
    language: {'url': WWW + '/assets/manager/js/datatables-spanish.json'},
    fnInitComplete: function() {
        this.fnAdjustColumnSizing();
        searchInit(this);
    }
});

$('.datatable').each(function() {
    var $this = $(this),
        pagination = ($this.find('tbody tr').length > 15);

    return $this.dataTable({
        bPaginate: pagination,
        bInfo: pagination
    });
});
```

After that, I'm using a custom search functions with string replacement:

```javascript
var searchInit = function ($datatable) {
    var $input = $datatable.closest('.dataTables_wrapper').find('.dataTables_filter input');

    if ($input.length === 0) {
        return false;
    }

    $.fn.dataTable.ext.search.push(function(settings, data, dataIndex) {
        var val = accentRemove($input.val().toLowerCase());

        for (var i = 0; i < data.length; i++) {
            var string = accentRemove($('<div/>').text(data[i]).text().toLowerCase());

            if (string.indexOf(val) !== -1) {
                return true;
            }
        }

        return false;
    });
}

var accentRemove = function (string) {
    return string
        .replace(/έ/g, 'ε')
        .replace(/[ύϋΰ]/g, 'υ')
        .replace(/ό/g, 'ο')
        .replace(/ώ/g, 'ω')
        .replace(/ά/g, 'α')
        .replace(/[ίϊΐ]/g, 'ι')
        .replace(/ή/g, 'η')
        .replace(/\n/g, ' ')
        .replace(/á/g, 'a')
        .replace(/é/g, 'e')
        .replace(/í/g, 'i')
        .replace(/ó/g, 'o')
        .replace(/ú/g, 'u')
        .replace(/ê/g, 'e')
        .replace(/î/g, 'i')
        .replace(/ô/g, 'o')
        .replace(/è/g, 'e')
        .replace(/ï/g, 'i')
        .replace(/ü/g, 'u')
        .replace(/ã/g, 'a')
        .replace(/õ/g, 'o')
        .replace(/ç/g, 'c')
        .replace(/ì/g, 'i');
};
```

The filter works fine, but my filter is applied AFTER datatables default filter, then to my filter can has not all available rows, only valid for previous datatables filter.

There are any way to disable the filter function without disable de input filter box?

I want to search only with my function.

Thanks a lot.

**Comment by ArturoMora** [comment]
We are in 2017 and the function accent neutralise of  datatables does not work with html tags? anyone has a idea about this?

**Comment by DataTables** [comment]
Thanks for the prompt - finally fixed now. Example: http://live.datatables.net/yunopaxe/2/edit

Moveover the next major version of DataTables should have this sort of thing built in.

**Comment by osoibol** [comment]
Hi! thanks for this great script and for the fix!

I added more accented letters to the script to make it more globally compatible (italian, french, german, and other languages accents, ie. ü ù ç ã ß ê ... )

You can watch the code here: https://jsfiddle.net/1xvrk09x/22/

The only problem is that if you look for 'ss' or 'SS' you get 'ß' content, but if you search for 'ß' content you wont find anything, anyone can help me fix this?
