### ISSUE TITLE
turkish-string plugin, Sorting Issue: "Uncaught TypeError: Cannot read property 'mData' of undefined" error

### ISSUE THREAD

**Issue by goktugicoz** [DataTables/Plugins#135]
DataTables v:1.10.4, turkish-string plug-in: cdn.datatables.net/plug-ins/9dcbecd42ad/sorting/turkish-string.js

$('#thinList').dataTable({
     'aoColumns' : [
                     {'sType' : 'turkish'}
     ]
 });

Error Details:

Uncaught TypeError: Cannot read property 'mData' of undefined jquery.dataTables.js:6365
(anonymous function) jquery.min.js:2
n.extend.eachjquery.dataTables.js:6362 
(anonymous function) jquery.min.js:2 
n.extend.eachjquery.min.js:2
n.fn.n.eachjquery.dataTables.js:6041
DataTable(index):1387
(anonymous function) jquery.min.js:2
j jquery.min.js:2
k.fireWith jquery.min.js:2
n.extend.ready jquery.min.js:2

Live sample: http://live.datatables.net/teqedice/1/edit

**Comment by mkaya93** [comment]
@goktugicoz I'm facing with same issue how did you solve it ?
