### ISSUE TITLE
Create a bower package

### ISSUE THREAD

**Issue by dr3am3r** [DataTables/Plugins#150]
Hello, @DataTables, 
It would be amazing to have plugins integrated in bower as well. 
It's like the only plugin I have to attach to the project by hand :) 
I can do PR if needed.

**Comment by DataTables** [comment]
Hi,

Thanks for the comment. I'm going to close this in favour of #81 which, at least implicitly, covers this. I need to spend some time on the extensions etc to get everything working with some of package managers that are available and writing up the documentation for it. Hopefully not to far in the future now.
