### ISSUE TITLE
On Selecting the Show All entries option, it displays record count instead of page number

### ISSUE THREAD

**Issue by Chinmay2412** [DataTables/Plugins#151]
When Show "All" entries is selected, in place of Page field, instead of page number record count is shown.

Solution:
1. Comment out the code from line 185 to line 190
2. Add the following code
 if( iPages <= 0) {
    iPages = 1;
 }
3. At the end of the for loop on line 198 add
 $(an).show();

**Comment by DataTables** [comment]
Thanks for the suggestion a nice and simple idea. Another option would be to use the the `infoCallback` option to customise the information message as needed.

I'm not going to fold this in at the moment as I actually prefer how it operates at the moment myself, but I'll leave this issue open for a while should anyone else wish to +1 this feature.

**Comment by DataTables** [comment]
Going to close now, but anyone else interested is welcome to chime in.
