### ISSUE TITLE
Collapsed information in responsive when a column has empty header

### ISSUE THREAD

**Issue by benbro** [DataTables/Plugins#153]
When I have a column with empty header, the responsive plugin show ":" in the description.
Usually it's:
```
column-header: cell content
```
But in case of empty header:
```
: cell content
```

In case of an empty column header we don't need the colon.

**Comment by DataTables** [comment]
Fixed in the [Responsive repo](https://github.com/DataTables/Responsive/commit/1ae4a7135373d8a475). Thanks for letting me know about this.
