### ISSUE TITLE
Duplicated header icons using bootstrap integration and scrollX and scrollY

### ISSUE THREAD

**Issue by albertsola** [DataTables/Plugins#159]
With bootstrap integration I get double icon lines. The first line of icons is in the right place on the header but there is another icons inside the first table body row.

Here you have an example: http://jsfiddle.net/a6mkevmt/

Datatables is adding the sorting icons as background so when the header is not visible it's not visible. In bootstrap integration the background get replaced by an element:after that it's shown. Display none is not working properly because then you loose the columns with.

I fix that replacing:

    table.dataTable thead .sorting:after {
    	opacity: 0.2;
    	content: "\e150"; /* sort */
    }
    table.dataTable thead .sorting_asc:after {
    	content: "\e155"; /* sort-by-attributes */
    }
    table.dataTable thead .sorting_desc:after {
    	content: "\e156"; /* sort-by-attributes-alt */
    }

For:

    *:not(.dataTables_scrollBody) > table.dataTable thead .sorting:after {
    	opacity: 0.2;
    	content: "\e150"; /* sort */
    }
    *:not(.dataTables_scrollBody) > table.dataTable thead .sorting_asc:after {
    	content: "\e155"; /* sort-by-attributes */
    }
    *:not(.dataTables_scrollBody) > table.dataTable thead .sorting_desc:after {
    	content: "\e156"; /* sort-by-attributes-alt */
    }

If someone found a better solution please let me know.

Thanks

**Comment by DataTables** [comment]
Hi,

Thanks for this. I think your fix is bob on. I'll merge it in and push it up to the repo first thing in the morning.

**Comment by gobisn** [comment]
hi, 
use this 
   "initComplete": function(settings, json) {
                $('.dataTables_scrollBody thead tr').css({visibility:'collapse'});
   }
