### ISSUE TITLE
Sorting icons are misplaced in Firefox (bootstrap and font-awesome integrator).

### ISSUE THREAD

**Issue by ant5** [DataTables/Plugins#162]
Firefox (24.5). In table header sorting glyphs all take one position after header row (not after header cell).
![bs](https://cloud.githubusercontent.com/assets/11061796/6250063/74660748-b79c-11e4-8f0a-ca79ac7be7d5.jpg)

![fa](https://cloud.githubusercontent.com/assets/11061796/6250097/a855eeb0-b79c-11e4-8121-790b20fb5e4e.jpg)

How to reproduce: open example files integration/bootstrap/3/index.html or integration/font-awesome/bootstrap.html.

Changing 'sorting_*:after' style  from "position: absolute" to "position: relative"  get glyphs into cell but not to the right place.

**Comment by DataTables** [comment]
Firefox 24 appears to suffer from [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=63895) where it fails to correctly position absolute elements in a table.

For old versions of Firefox you could try using an old release of the plug-ins which doesn't use font icons in the same way as the current release. For example: http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/ .
