### ISSUE TITLE
Ajax Setup conflict

### ISSUE THREAD

**Issue by Braunson** [DataTables/Plugins#163]
I have the following..

```javascript
    var spinner = $('#load-spinner');
    $.ajaxSetup({
        // Setup our CSRF header for every ajax call
        headers: {
            'X-CSRF-Token': $('meta[name="_token"]').attr('content')
        },
        beforeSend: function(jqXHR, settings) {
            spinner.fadeIn();
        },
        success: function(response, textStatus, jqXHR) {
            //console.log(response);
        },
        complete: function(response, textStatus, jqXHR) {
            spinner.fadeOut();
        },
    });
```

And I'm using data tables like so..

```javascript
    var dt = table.DataTable({
        'ajax': '/api/jobs/datatable'
    });

    function reloadJobs() {
        dt.ajax.reload(null, false);
    }

    setInterval(function() {
        reloadJobs();
    }, 1000);
```

I want to overwrite the ajax setup to show/hide the spinner on every ajax call for any dataTable calls. I've searched through the docs on how to add this to dataTable only calls but have had no luck.

```javascript
    beforeSend: function(jqXHR, settings) {}
    complete: function(response, textStatus, jqXHR) {}
```

Any ideas?

**Comment by DataTables** [comment]
I'm not entirely sure why this is posted here? Could you ask support questions in the [DataTables forums](//datatables.net/forums) in future please.

It sounds like you want to use the [`ajax` option as an object](http://datatables.net/reference/option/ajax#object) and pass in the beforeSend and complete options.

Another option, which I think would probably be better, would be to listen for the `processing` events: http://datatables.net/reference/event/processing .

Allan
