### ISSUE TITLE
dataTables.jqueryui.css line #337 specifies a color with a !important override

### ISSUE THREAD

**Issue by cookch10** [DataTables/Plugins#166]
I was in the process of upgrading my dataTables.jqueryui.css file when I noticed that some colors in my DataTables implementation had changed.  I tracked the culprit to line 337 of https://github.com/DataTables/Plugins/blob/master/integration/jqueryui/dataTables.jqueryui.css

```css
color: #333333 !important;
```

Was this style override intentional?

**Comment by DataTables** [comment]
I'm fairly sure that used to be required to have the text of the pagination buttons visible. It looks like it no longer is needed with the latest versions of jQuery UI's theme roller files. I think it can be dropped.

**Comment by DataTables** [comment]
Committed here - ed6340ced4ec82d539 . Thanks for flagging this up.

**Comment by cookch10** [comment]
:thumbsup:
