### ISSUE TITLE
Expand accepted numeric formats

### ISSUE THREAD

**Issue by mmangione** [DataTables/Plugins#173]
I use this plugin on data columns that are currencies which are formatted to be human-readable. I made the following modification to the code:

jQuery.fn.dataTable.Api.register( 'sum()', function () {
    return this.flatten().reduce( function ( a, b ) {
	var a = String(a).replace(/[^\d.-]/g,'');
	var b = String(b).replace(/[^\d.-]/g,'');
        return (a*1) + (b*1); // cast values in-case they are strings
    } );
} );

Perhaps this would be useful for others?

**Comment by DataTables** [comment]
Yes sounds like a good suggestion. Perhaps there should be a parameter for stripping formatting - `if ( strip ) { ... }` so the developer effectively acknowledges that this will happen.

Not sure if that is a good idea or not... :-)

**Comment by mmangione** [comment]
I was debating a parameter like that also. I too am uncertain. 

For my own use, it just seemed like I would probably use the strip parameter all the time. In that instance, it just seemed like extra work.

**Comment by DataTables** [comment]
I've [just committed the change](https://github.com/DataTables/Plugins/commit/984aa9c54b98) for this.

I decided I liked your approach best - just strip everything. If the develop passes in the wrong data (selecting the wrong column for example) that is their bug and the benefit of doing this is worth it for convenience!
