### ISSUE TITLE
no room for pagination for big lists

### ISSUE THREAD

**Issue by jnylund** [DataTables/Plugins#174]
Hi,

I have a problem, when I have the searchbox enabled, I get the col-xs-6 injected for parent divs for the top and the bottom (top search area and number of items), bottom search stats and pagination.

My pagination doesn't fit when this happens. See attached picture. When I turn search off pagination is on the next line after stats and it is fine. What can I do to work around this? Can I control the pagination classes? The bootstrap js files are within a gem so it is hard for me to override them.

![screen shot 2015-03-23 at 8 22 29 am](https://cloud.githubusercontent.com/assets/45084/6779790/f778197a-d135-11e4-87c3-108420d7471b.png)

(note this is for bootstrap plugin, sorry if this is not the right place)

**Comment by DataTables** [comment]
Looks like you are also loading the DataTables default CSS. Remove that.

In future, can you post support requests in the [DataTables forums](//datatables.net/forums) please.
