### ISSUE TITLE
Plugins - type-detection - file-size.js

### ISSUE THREAD

**Issue by MrMikeJJ** [DataTables/Plugins#175]
Hi,
I've just been trying to use 
Plugins/type-detection/file-size.js
and have come across a issue with it not handling a decimal point in the number field.

This works, but can probably be done better :)
```
		var sValidChars = "0123456789";
		var Char;
		var fullstop;

		/* Check the numeric part */
		for ( var i=0 ; i<(sData.length - 3) ; i++ )
		{
			Char = sData.charAt(i);
			if (sValidChars.indexOf(Char) == -1)
			{
				if (!fullstop && Char == ".") {
					fullstop = true;
					continue;
				}
				return null;
			}
		}
```

**Comment by DataTables** [comment]
Thanks for this. I've been meaning to rewrite that plug-in actually - I'll make sure a decimal point is handled!

**Comment by MrMikeJJ** [comment]
Great, that's good to know. And thanks for the quick response :)

**Comment by DataTables** [comment]
Rewrite of the plug-ins [now committed](https://github.com/DataTables/Plugins/commit/9c2e4075353).

Example here: http://live.datatables.net/cesuvido/1/edit
