### ISSUE TITLE
repository name 'plugins'

### ISSUE THREAD

**Issue by ltdeta** [DataTables/Plugins#176]
is it possible to change the repository name from "plugins" to "DataTable-plugins" ?

using the feature ```cloning on desktop``` or ```Download ZIP``` the name likes only ```plugins```
names like:
aaaaaaa   bbbbbbbb
------------ | -------------
button-Donwload  | ```Plugins-master.zip```  | ```DataTables-Plugins-master.zip```
button Clone on Desktop  | Github name is ```Plugins```  | ```DataTable-Plugins```

**Comment by DataTables** [comment]
That would create all sorts of compatibility issues with projects that already using it with its current name, so I would rather not do that.

You could if you wanted fork it and use a name that is suitable for your use.

**Comment by ltdeta** [comment]
ok
