### ISSUE TITLE
Pagination controls wrap in bootstrap3

### ISSUE THREAD

**Issue by fisharebest** [DataTables/Plugins#179]
The status and pagination controls each have exactly 50% of the footer width.

This comes from the `dom` parameter `"<'row'<'col-sm-6'i><'col-sm-6'p>>"`

Increasing the number of rows in the sample page causes the pagination control to wrap.

![untitled](https://cloud.githubusercontent.com/assets/2306088/6917010/b4fe915a-d798-11e4-8c64-315e6da66a35.png)

It might be better to distribute the space differently: `"<'row'<'col-sm-5'i><'col-sm-7'p>>"`.

**Comment by DataTables** [comment]
Sounds like a good idea to me. What we really need is some flex box goodness. That would handle it nicely :-).
