### ISSUE TITLE
Polish translate issues

### ISSUE THREAD

**Issue by meron1122** [DataTables/Plugins#181]
If i remove comment from Polish.lang , translate load very well, if comment starts fille translate dont load.
Why?
Datatables 1.10.5
Datatables plugins this same version

**Comment by DataTables** [comment]
The `.lang` files are not valid JSON. You need to remove the comments (which include meta data) if you want to use them as JSON, or include them from the DataTables CDN which already have them as valid JSON.

**Comment by meron1122** [comment]
So, if i want manage via bower for example and have internet independent app is any good way?

**Comment by DataTables** [comment]
Currently you would need to modify the files to make then valid JSON.

I plan to update them to store the meta data else where in future.

**Comment by ramilexe** [comment]
@DataTables +1 for this feature
