### ISSUE TITLE
Search Filter Missing Clear Filter Button

### ISSUE THREAD

**Issue by JohnRoach** [DataTables/Plugins#186]
When one enters a search within the search box a "X" appears so users can click on and clean Search input box. This doesn't happen when Bootstrap plugin is installed.

**Comment by DataTables** [comment]
That is how Bootstrap styles `<input type="search"/>` input elements I'm afraid: http://jsfiddle.net/73y9oe59/ . It would be incorrect of the integration CSS to override what Bootstrap does by default there, but you could modify (or override) Bootstrap to have it show the way you want.

**Comment by gregmac** [comment]
Issue in bootstrap: https://github.com/twbs/bootstrap/issues/5624
