### ISSUE TITLE
pageResize Plugin - Divide by Zero when Datatable hidden

### ISSUE THREAD

**Issue by williamdenton** [DataTables/Plugins#188]
When the datatable is created in a hidden div and then shown, the pageResize plugin fails and breaks normal display of grid.

    var rowHeight = $( 'tr', settings.body ).eq(0).height();

rowHeight is zero when the datatable parent container is `display:none`

    var drawRows = Math.floor( availableHeight / rowHeight );

this check could check for `NaN` so normal grid functionality is not broken

		if ( drawRows !== dt.page.len() ) {
			dt.page.len( drawRows ).draw();
		}

Reproduced in Chrome.

**Comment by DataTables** [comment]
Thanks for letting me know about this :-)
