### ISSUE TITLE
Seems like PageResize plugin doesn't work in the latest Firefox

### ISSUE THREAD

**Issue by smartcorestudio** [DataTables/Plugins#189]
Look at the screenshot of your demo. There are no js errors in console
![2015-04-29 12_30_13-vertical page fitting](https://cloud.githubusercontent.com/assets/2891792/7388126/7ce6bc7c-ee6b-11e4-9666-001ce1572bfe.png)
![2015-04-29 12_29_37-vertical page fitting](https://cloud.githubusercontent.com/assets/2891792/7388127/7ceb5566-ee6b-11e4-83d6-f5a486b3fa91.png)

(Everything is OK in Blink-based browser)

**Comment by DataTables** [comment]
Thank for reporting this. I actually committed a fix just about an hour ago based on [the discussion here](https://www.datatables.net/forums/discussion/27504). The latest source in this repo does not suffer from this problem in Firefox.
