### ISSUE TITLE
conditionalPaging: won't apear after lengthMenu dropdown changed

### ISSUE THREAD

**Issue by ltdeta** [DataTables/Plugins#190]
the not working example [jsfiddle](http://jsfiddle.net/ltdeta/rstbyap9/)

1. change the ``lengthMenu`` dropdown to ``all`` the ``paging-menu`` disapear => ok
2. change the ``lengthMenu`` dropdown to a option less than ``all`` the ``paging-menu`` won't apear => error?

here are the working [jsfiddle](http://jsfiddle.net/ltdeta/8y0g4aso/1/)
i added the source (conditionalPaging) from cdn and extend it

**Comment by DataTables** [comment]
@mjhasbach - Might you be willing to take this one?

**Comment by ltdeta** [comment]
sorry, i do not understand

**Comment by DataTables** [comment]
@mjhasbach wrote that plug-in and I was wondering if he might be willing to take a look at your bug.
