### ISSUE TITLE
Sum returning the total set of data in a column even after filtering the table.

### ISSUE THREAD

**Issue by arunnambissan** [DataTables/Plugins#203]
I have used the following code to display the total of price column in my datatable
var tot = table.column( 1 ).data().sum();
$('#amount_total').text('= $' + tot);

It is working without any issue.
But after filtering the table based on some fields like daterange, the sum of all data is returned. I have checked that in every filtering event I have called the above code for sum. Please help me out. Thank You

**Comment by DataTables** [comment]
In future, please post support requests in the [DataTables forums](//datatables.net/forums).

To answer your question use the [`selector-modifier` option](http://datatables.net/reference/type/selector-modifier) of the [`column()` method](http://datatables.net/reference/api/column) to tell DataTables what rows to include.
