### ISSUE TITLE
lengthLinks feature-plugin breaks when using stateSave and show all lengthMenu

### ISSUE THREAD

**Issue by malte-witt** [DataTables/Plugins#210]
When using stateSave and the lengthLinks feature plugin in conjunction with a show all (-1) option in aLengthMenu, the lengthLinks output isn't rendered on the initial draw callback after a page reload.

The problem seems to be located in [this part](https://github.com/DataTables/Plugins/blob/f954372e84aa850d2137ea04114c15875ad9f9da/features/lengthLinks/dataTables.lengthLinks.js#L56) of the lengthLinks plugin:
```
var lastLength = -1;

// [...]

	// No point in updating - nothing has changed
		if ( api.page.len() === lastLength ) {
			return;
		}
```

Steps to reproduce:
- goto https://jsfiddle.net/fkbx0f9o/2/
- change length to "all" using either of the both methods,
- reload the page

---> "L" length menu is gone, "l" length menu is still there.

**Comment by DataTables** [comment]
Thanks for letting me know about this and the test case. This is an [updated fiddle with the fix](https://jsfiddle.net/fkbx0f9o/3/).
