### ISSUE TITLE
Issue with Reponsive DataTables and Bootstrap

### ISSUE THREAD

**Issue by alliquot** [DataTables/Plugins#228]
Hello,

I faced two issues:

1. When I'm expanding previously shrunken page, contained table switches from "collapsed" form to the "normal" one (as expected) but remains narrow. I have to refresh the page to make the table again 100% width.

Screenshot 1: "collapsed" form (OK)
![collapsed] (http://s3.postimg.org/9kbwzl11f/dt_issue_1.png)

Scr 2: form switched (OK)
![switched] (http://s3.postimg.org/d2nwvz1xf/dt_issue_2.png)

Scr 3: ...but remains narrow after resizing the output (WRONG)
![narrow] (http://s3.postimg.org/cbv6q6zk3/dt_issue_3.png)

Scr 4: and how it should look like:
![shoulbe] (http://s11.postimg.org/5jsst5qn7/dt_issue_0.png)

2. there are 2 different glyphs in the header
![doubled] (http://s3.postimg.org/peqt9gps3/dt_issue_4.png)

Example with all attached JS and CSS, according to the "Download" page. Please change the width of the output panel to see the issue:

https://jsfiddle.net/t5h2wwop/

Tested under newest FF and Chrome.

---

Temporary workaround which makes the "reponse" smooth and working:

    $(window).on('resize', function(){
    	$('#myTable').width('100%');
    	});

**Comment by DataTables** [comment]
This works with the nightly versions of DataTables and Responsive: https://jsfiddle.net/t5h2wwop/1/ . Both of which I plan to release later this week.
