### ISSUE TITLE
search highlight doesn't highlight if the matched term is in child row

### ISSUE THREAD

**Issue by vafada** [DataTables/Plugins#237]
If the search term is inside a child row (e.g using responsive plugin), the rows are filtered correctly, but when you open the child row (https://datatables.net/examples/api/row_details.html) the search term isn't highlighted

**Comment by DataTables** [comment]
Hi - this is expected. The highlight plug-in doesn't consider child rows at the moment, only the main table rows. Pull requests welcome if you want to add that feature though :-)

**Comment by vafada** [comment]
:cry: 

I have a workaround but its using the responsive plugin since the responsive plugin triggers an event when the child is shown or hide.

**Comment by DataTables** [comment]
like a good idea. Perhaps you could post your change so anyone else who wants to do this can also benefit from it.
