### ISSUE TITLE
scrollToRow problem with 'table-condensed' style

### ISSUE THREAD

**Issue by dflickcb** [DataTables/Plugins#250]
I have a table with a couple of hundred rows styled `<table id="tripActivationTable" class="table table-condensed table-striped table-bordered table-hover">` . When I use scrollToRow to position on a a particular row it is not visible in the view.  If I remove `table-condensed` then it appears in the view assume something to do with padding. Any ideas how to work around this?  Note: using datatables.bootstrap.css

**Comment by DataTables** [comment]
Can you link to a page showing the issue please.

**Comment by dflickcb** [comment]
Unfortunately it is not a public app. I will put together a stand alone version that hopefully shows the same behavior and update this post when ready.
