### ISSUE TITLE
Footer Total repeating

### ISSUE THREAD

**Issue by Zaeembinrehman** [DataTables/Plugins#261]
Hello There, 

There is total displayed at the bottom of the table. On the web page, it looks fine.
![screenshot_60](https://cloud.githubusercontent.com/assets/15250782/14494405/2fbb5b2c-01a4-11e6-9fe2-2b34ebcb45f5.png)

But when exported to any file format (csv, pdf ) the values gets repeated.

![screenshot_61](https://cloud.githubusercontent.com/assets/15250782/14494452/5ae0565e-01a4-11e6-96df-6053de0a5b7a.png)

The JS code:

`var table = $(".reports .dataTable");
    table.DataTable({
        "dom": 'T<"clear">lfrtip',
        "bPaginate": false,
        "tableTools": {
            "sSwfPath": baseurl + "/js/plugins/dataTables/swf/copy_csv_xls_pdf.swf",
            "aButtons": [ "copy", "csv", "xls", { "sExtends": "pdf", "sTitle": "Report "+new Date($.now()) }, "print" ]
        },
        "footerCallback": function ( row, data, start, end, display ) {
            var api = this.api(), data;
            // Remove the formatting to get integer data for summation
            var intVal = function ( i ) {
                return typeof i === 'string' ?
                i.replace(/[\$,]/g, '')*1 :
                    typeof i === 'number' ?
                        i : 0;
            };
            // Total over all pages
            total = api
                .column( 4 )
                .data()
                .reduce( function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0 );

            // Total over this page
            pageTotal = api
                .column( 4, { page: 'current'} )
                .data()
                .reduce( function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0 );

            // Update footer
            $( api.column( 4 ).footer() ).html(
                '&pound'+ Math.round(pageTotal * 100) / 100 +' ( &pound'+ Math.round(total * 100) / 100 +' total)'
            );
            //$( api.table().footer() ).html(
            //    'Total: ' + api.column( 4, {page:'current'} ).data().sum()
            //);
        }
    });`

The footer mark up of table:
`<tfoot>
                    <tr>
                        <th colspan="4" style="text-align:right">Total:</th>
                        <th colspan="4" ></th>
                    </tr>`

what could be the reason of it? Thanks.

**Comment by DataTables** [comment]
Hi,

Could you post support questions in the [DataTables forums](//datatables.net/forums) please? That way they are all searchable in a single location.

Please also ensure that you link to a running test case which can be debugged.
