### ISSUE TITLE
Problem with translation 

### ISSUE THREAD

**Issue by kossa** [DataTables/Plugins#267]
Hi,

I want to use datatables in french, here is the code :

```
var table = $('.data-tables').DataTable({
	'language' : {
		"url" : "PATH_TO/French.lang"
	}
});
```

But It doesn't work, If I delete the comment at the top it works fine!!!

Whats' the problem ?

**Comment by DataTables** [comment]
Use the [version on the CDN](http://cdn.datatables.net/plug-ins/1.10.11/i18n/French.json) which doesn't have that meta data.

**Comment by kossa** [comment]
@DataTables, Please can you explain me why it doesn't work ? 

I'm using Bower to manage my packages, so I don't want to use extranel link, but if it's the only solution NP ;)

**Comment by DataTables** [comment]
For exactly the reason you state. The file has a comment at the top which is not valid JSON. The version on the CDN removes that meta data so it can be included on a page as JSON.

**Comment by kossa** [comment]
Thank you

**Comment by marcelod** [comment]
I have a question that is because it has the repository or file .json or file .lang without comments and in a project I'm using bower and it ends up not helping me.
Thank you
