### ISSUE TITLE
Pagination styling not using bootstrap styling

### ISSUE THREAD

**Issue by Mentos93** [DataTables/Plugins#268]
The pagination of my DataTable is not styled. This is how it currently looks;

![screenshot from 2016-06-03 13 48 21](https://cloud.githubusercontent.com/assets/16900286/15777964/765f5b66-2993-11e6-9afe-9e71c1a364aa.png)

Why doesn't it looks like the bootstrap styling like [here](https://datatables.net/manual/styling/bootstrap-simple.html)?

The CSS files I have;

```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
<link href="/css/styling.css" rel="stylesheet">
```

And my JavaScript files;
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function() {
        $('#index-table').DataTable({
            "dom": '<<"col-md-3"i><"col-md-3"><"col-md-3"><"col-md-3"f>><t><<"col-md-3"l><"col-md-3"><"col-md-3"><"col-md-3"p>>'
        });
    });
</script>
```

**Comment by DataTables** [comment]
My apologies if the template text in the _New Issue_ textbox and also the information in the Contributing document aren't clear enough. Please post support requests in the DataTables forums and also link to a test case showing the issue.

In this case, you've not loaded the DataTables / Bootstrap JS file. I would suggest using the [downloader](//datatables.net/download) to make sure you get all the files you required.
