### ISSUE TITLE
Input pagination - Page Turning Error

### ISSUE THREAD

**Issue by JisaKun** [DataTables/Plugins#275]
http://codepen.io/JisaKun/pen/mPZJmB?editors=1010

Here is my demo, there is six pages in table ,when I input a number like 7 and expect table turn to page 6,while it turn to page 5.

It happens when page 6 contain only one record.

Why ~?

**Comment by DataTables** [comment]
Looks like a bug - thanks for flagging it up. I'll try to take a look at some point, but can't say when I'm afraid. Pull requests welcome :-)
