### ISSUE TITLE
console.log in dataTables.pageResize.js

### ISSUE THREAD

**Issue by gbsmit03** [DataTables/Plugins#283]
This is a minor thing but can we remove the `console.log( drawRows );` statement on line 86 in dataTables.pageResize.js ?

[dataTables.pageResize.js - line 86](https://github.com/DataTables/Plugins/blob/master/features/pageResize/dataTables.pageResize.js#L86)

**Comment by DataTables** [comment]
Thanks for pointing that out! Embarrassing :-)

**Comment by gbsmit03** [comment]
No problem and thanks for the quick update.
