### ISSUE TITLE
server side pagination with solr and php

### ISSUE THREAD

**Issue by amr1tv1rd1** [DataTables/Plugins#289]
Hi , I have been looking for server side pagination for DataTables with php and solr. Could you help me code snippet ?

**Comment by DataTables** [comment]
If you need someone to develop code for you, you might want to try Elance, ODesk or similar. I'm afraid I'm not taking on any contracting work at the moment as I'm focusing on bringing new features to DataTables.

**Comment by amr1tv1rd1** [comment]
Thanks
