### ISSUE TITLE
 When using fnReloadAjax does not remain on the current page

### ISSUE THREAD

**Issue by marcelod** [DataTables/Plugins#294]
I am using the [fnReloadAjax](https://github.com/DataTables/Plugins/blob/master/api/fnReloadAjax.js) to do some action when the datatable, just not stay on the current page. It keeps the filter, sort, the number of records per page, but always comes back to the first page.

Does anyone know of anything to solve it?

**Comment by DataTables** [comment]
would suggest you use the built in [`ajax.reload()` method](https://datatables.net/reference/api/ajax.reload()) rather than that legacy plug-in.

If the API method isn't working for you, please open a new thread in the DataTables forums with a link to a test page showing the issue.

**Comment by marcelod** [comment]
Thank you, I got so using `oTable.api().ajax.reload(null, false);`
