### ISSUE TITLE
Select text missing from i8n

### ISSUE THREAD

**Issue by barchard** [DataTables/Plugins#307]
It looks like the "1 row selected" text is missing from the translation files. Is this text translatable?

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/17622/20651307/d3a4a62a-b4b0-11e6-8f3a-c444fd6418ae.png)

**Comment by DataTables** [comment]
Its part of the Select plug-in, which is why it isn't in the DataTables core translation files. The config option for it (and all other options) can be found in the reference: https://datatables.net/reference/option/language.select.rows .

**Comment by barchard** [comment]
Thanks. Is there a JSON URL available like the code language files?

**Comment by DataTables** [comment]
http://cdn.datatables.net/plug-ins/1.10.12/i18n/
