### ISSUE TITLE
require("datatables-bootstrap") in commonjs / node loader fails due to incorrect factory function call

### ISSUE THREAD

**Issue by ollycross** [DataTables/Plugins#308]
I'm trying to use DataTables.Bootstrap with Browserify so I `require("datatables")` then `require("datatables-bootstrap)`, but the latter call fails because with a `DataTable.ext is undefined` error.

This is because the commonjs loader in the bootstrap plugin calls it's factory function with `factory(require("jquery"), require("datatables"))` but as noted here https://datatables.net/download/npm the `require("datatables")` returns a function rather than the DataTable object.

I have fixed this in my dev by changing the factory call to `factory(require("jquery"), require("datatables")())` - note the trailing parentheses, and am happy to make a pull request to this effect but to be honest I'm not knowledgeable enough about commonjs, node and factory functions to know whether this would break something elsewhere!

I think this is related to https://github.com/DataTables/Plugins/issues/122

**Comment by DataTables** [comment]
Could you use `datatables.net` rather than just `datatables` please? Also the fact that you need to execute the module is so you have the option of passing in a window or jQuery object. That is documented [on this page](https://datatables.net/download/npm).

**Comment by ollycross** [comment]
Ah righty, got ya.  Knew I was missing something!

Thanks :)
