### ISSUE TITLE
Internationalisation - Filter placeholder "All"

### ISSUE THREAD

**Issue by tatapoum** [DataTables/Plugins#311]
Hi, 
I have not found in the documentation the parameter to internationalise the placeholder in the filter input.
https://datatables.net/reference/option/language

By default, it has the value "All" that I would like to translate.

**Comment by DataTables** [comment]
Sounds like [`language.searchPlaceholder` is the one you want](https://datatables.net/reference/option/language.searchPlaceholder). In future, pelase ask support questions in the DataTables forums. Thanks!
