### ISSUE TITLE
PageResize Plugin: Hover callback is fired multiple times on a single hover.

### ISSUE THREAD

**Issue by dzackgarza** [DataTables/Plugins#317]
I've made a JSFiddle to illustrate the issue here: https://jsfiddle.net/dzackgarza/88kg4pq7/

If you run this fiddle, then hover over a row, you'll see that the console.log message is printed multiple times. Is there any way to prevent this behavior?

**Comment by DataTables** [comment]
Yeah - don't attach events in `rowCallback` :-). It is called every single time a row is drawn, and as you resize the container the table is being redrawn, hence the issue.

You could use `createdRow`, or even better would be to use a delegated event.
