### ISSUE TITLE
i18n not well-formed

### ISSUE THREAD

**Issue by soulflyman** [DataTables/Plugins#324]
If I try to use one of the i18n files, I get the following error:

> XML Parsing Error: not well-formed
Location: http://localhost:8000/templates/webdat-v1.3.0/vendors/datatables.net-plugins/i18n/German.lang
Line Number 1, Column 1:  German.lang:1:1

To get it working, I had to rename the .lang to .json and use it like this in my code
```
   $('#example').DataTable( {
        "language": {
            "url": "http://localhost:8000/templates/webdat-v1.3.0/vendors/datatables.net-plugins/i18n/German.lang.json"
        }
    } );
```

I also had to change the names of the elements in the json.
```{
  "decimal":        ",",  
  "emptyTable":     "Keine Daten vorhanden",  
  "info":           "_START_ bis _END_ von _TOTAL_ Einträgen",
  "infoEmpty":      "0 bis 0 von 0 Einträgen",
  "infoFiltered":   "(gefiltert von _MAX_ Einträgen)",
  "infoPostFix":    "",
  "thousands":      ".",
  "lengthMenu":     "_MENU_ Einträge anzeigen",
  "loadingRecords": "Wird geladen...",
  "processing":     "Daten werden verarbeitet, bitte warten...",
  "search":         "In Tabelle suchen:",
  "zeroRecords":    "Keine passenden Einträge vorhanden.",
  "paginate": {
    "first":      "Erste",
    "last":       "Letzte",
    "next":       "Nächste",
    "previous":   "Zurück"
  },
  "aria": {
    "sortAscending":  ": aktivieren, um Spalte aufsteigend zu sortieren",
    "sortDescending": ": aktivieren, um Spalte absteigend zu sortieren"
  }
}
```

After doing all this it works. So why don't we fix the repository that it is easier to use out of the box?

**Comment by DataTables** [comment]
There is some discussion on this [in this issue](https://github.com/DataTables/Plugins/issues/131).

The files in the repo contain meta data as well as raw raw - they are not JSON files. They will indeed throw an error if you attempt to include them directly from the repo without any kind of processing.

They are available on the [DataTables CDN](https://cdn.datatables.net/plug-ins/1.10.13/i18n/) as JSON files and can be included from there.
