### ISSUE TITLE
gh-pages don't open

### ISSUE THREAD

**Issue by YeomanYe** [DataTables/Plugins#325]
I click gh-pages in the code tab,but occur 404 not found

**Comment by DataTables** [comment]
There are no gh-pages published for this repo.

**Comment by YeomanYe** [comment]
Thanks.Could you tell me how to generate gh-page button?

**Comment by DataTables** [comment]
As I say, there are no GitHub pages for this repo. If you need help with GitHub pages in general, I'd suggest checking out their documentation.

**Comment by YeomanYe** [comment]
ok,I see
