### ISSUE TITLE
Turkish-string plugin

### ISSUE THREAD

**Issue by mkaya93** [DataTables/Plugins#326]
Hi,

I'm getting this error. When I trying to sorting tables with turkish characters with that plugin.

> Uncaught TypeError: Cannot read property 'mData' of undefined
>     at HTMLTableCellElement.<anonymous> (jquery.dataTables.js:1197)
>     at Function.each (jquery.min.js:2)
>     at n.fn.init.each (jquery.min.js:2)
>     at HTMLTableElement.<anonymous> (jquery.dataTables.js:1194)
>     at Function.each (jquery.min.js:2)
>     at n.fn.init.each (jquery.min.js:2)
>     at n.fn.init.DataTable [as dataTable] (jquery.dataTables.js:869)
>     at n.fn.init.$.fn.DataTable (jquery.dataTables.js:15104)
>     at HTMLDocument.<anonymous> (jquery-datatable.js:25)
>     at i (jquery.min.js:2)

```
$('.js-basic-example').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.13/i18n/Turkish.json"
        },
        'aoColumns' : [
            {'sType' : 'turkish'}
        ]

    });
```

**Comment by hazarkarabay** [comment]
The `aoColumns` parameter and plug-in description is no longer valid, you'll need to use `columnDefs`. 

For example, if you want to use Turkish sorting for all columns:
```
columnDefs: [
    {type: 'turkish', targets: '_all'}
]
```

**Comment by DataTables** [comment]
Thanks!

[Committed here](https://github.com/DataTables/Plugins/commit/dd92884ce73305918385df14f55abb583ec1063d).

**Comment by gokselb** [comment]
Thank you!
