### ISSUE TITLE
Use .json extension instead of .lang in datatables.net-plugins npm package

### ISSUE THREAD

**Issue by brunobertechini** [DataTables/Plugins#338]
In order to maintain a standard, could you please update the package in npm (datatables.net-plugins) to use i18n language files as json ?

This is needed because .json is more-than-standard mimetype for every web application.

.lang files are not recognized as json by default.

If needed, maybe provide both options in the package?

Bruno

**Comment by DataTables** [comment]
HI Bruno,

There is #192 for this already. I've not had a chance to do it yet, but it will happen alongside other things.

**Comment by brunobertechini** [comment]
Thanks
