### ISSUE TITLE
how to import datatables with es6

### ISSUE THREAD

**Issue by lvliang271486017** [DataTables/Plugins#340]

**Comment by eleggua999** [comment]
It could be possible.
Get plugins package with nmp:
```npm install datatables.net-plugins```
Create file, ex. translations.dataTables.js, with:
```
export function initDataTableTranslations() {
    return require('datatables.net-plugins/i18n/German.lang');
}
```
And in another file:
`import { initDataTableTranslations } from './translations.datatables.js'`
But translation files have, khm, 'comments' at the beginning, and JSONs don't have comments, so this doesn't compile and the only option is to get it from cdn or make your own files.

**Comment by DataTables** [comment]
Closing in favour of #352.
