### ISSUE TITLE
Column Resize Extension

### ISSUE THREAD

**Issue by smasala** [DataTables/Plugins#341]
Not really a plugin, but an extension; modelled after https://github.com/DataTables/ColReorder

https://github.com/smasala/ColResize
Allows the user to resize the column with simple draging actions.

Demo found in project under:
examples/index.html

**Comment by DataTables** [comment]
Really really superb! Thank you for sharing this with the world!

**Comment by smasala** [comment]
@DataTables You're more than welcome to pull it into the DataTables repo world if you like.

**Comment by smasala** [comment]
Live Demo: https://smasala.github.io/ColResize/
