### ISSUE TITLE
select translation

### ISSUE THREAD

**Issue by DJmRek** [DataTables/Plugins#343]
is it ok to add select translations in the language files? (if yes i could make a pull request for german.lang)

**Comment by DataTables** [comment]
That would be great - thanks.

I think the approach I'm going to take is that the core DataTables options much be included in the translation files, but the other extensions' options can be optional. If they are available, then that is of benefit to all!

**Comment by DJmRek** [comment]
Thnaks for merging. One last question: I read in some other PRs that the 'new' style for the keys is camelcase (e.g. old: sEmptyTable | new: emptyTable). Is it okay for you if i chnage that?

**Comment by DataTables** [comment]
You are correct. For the moment I want to retain what old style there is. With the next major update of DataTables I'll convert it to the new style. Just for backwards compatibility.
