### ISSUE TITLE
Error on add a langage apart default

### ISSUE THREAD

**Issue by hnahoulder** [DataTables/Plugins#367]
I'm trying to add to add an option to datatable
language: {
                "url": "http://cdn.datatables.net/plug-ins/1.10.16/i18n/French.json"
            }
The modification of language is considered by datatable but a have an error. An then I can't use the table created. The error is, do you have an idea:
dataTables.select.js:306 Uncaught TypeError: Cannot read property 'selector' of undefined

**Comment by DataTables** [comment]
Works [okay here](http://live.datatables.net/vemobeve/1/edit). Please link to a test case showing the issue. Also, in future, please port support requests in the [DataTables forums](//datatables.net/forums).

**Comment by szakitibi** [comment]
![image](https://user-images.githubusercontent.com/13345340/53000693-3b050900-3429-11e9-90a3-303b0b0de187.png)

**Comment by DataTables** [comment]
Yes, there is a bug in the JSON of the current French translation's JSON. That has been [fixed in this repo already](https://github.com/DataTables/Plugins/commit/20616e533560bbffc30e1087b4985f41dee3635a#diff-3ee9d414fad063c187cad68133c0acd9) and will be in the next release.
