### ISSUE TITLE
SearchPane Issue with Multiple Selections and Table Filtering

### ISSUE THREAD

**Issue by ChrisDrozdowski** [DataTables/Plugins#371]
When selecting more than one item in a SearchPane, sometimes too many items are included in the table.

Steps to reproduce:
1. Go to this JSFiddle: https://jsfiddle.net/0vzythw0/3/
2. Run the Fiddle.
3. In the "Sheet" SearchPane, select Sheet1 and Sheet2.

Notice in table that Sheet1, Sheet11, and Sheet2 are displayed. This is the issue. I would think only Sheet1 and Sheet2 would be displayed.

I notice that if I modify the un-minimized source code as follows (see comments), it works correctly. But I am not sure if it would break other user stories.
```
.column(pane.data('column'))
.search(
	'^(' + // NOTICE ADDITION OF "("
		$.map(filters, function(filter) {
			var d = $(filter)
				.data('filter')
				.toString();
			return $.fn.dataTable.util.escapeRegex(d);
		}).join('|') +
		')$',  // NOTICE ADDITION OF ")"
	true,
	false
)
```

**Comment by DataTables** [comment]
Thanks for pointing that out - looks like a good fix.

**Comment by ChrisDrozdowski** [comment]
Hi,

Based on my own testing, there needs to be an additional modification based on change.
This code:
```
search = search ? search.substr(1, search.length - 2).split('|') : [];
```
Needs to be modified to:
```
search = search ? search.substr(2, search.length - 4).split('|') : [];
```
I hope this helps.
~Chris

**Comment by DataTables** [comment]
I'm not fully clear on why that is, btu I'll take a look into it as this is prompted to be an extension for DataTables.

**Comment by ChrisDrozdowski** [comment]
It is because when the parentheses characters were added at the beginning and end of the regular expression in my original comment, that changed how the substring needs to be calculated to remove them.
