### ISSUE TITLE
SearchPane Feature Request: Options for Item Selection Including 'os' and 'multi+shift'

### ISSUE THREAD

**Issue by ChrisDrozdowski** [DataTables/Plugins#372]
For SearchPane, please consider adding support for item selection options including  'os' and 'multi+shift' styles.

This can allow SearchPane to have same behavior as the Select plugin.

**Comment by DataTables** [comment]
Thanks! I've added this [to the list of enhancements in the thread tracking this](https://datatables.net/forums/discussion/46119/searchpane-feedback#latest).
