### ISSUE TITLE
Datatable Accent neutralise and Diacritics-neutralise-sort plug-in

### ISSUE THREAD

**Issue by luisdesouza** [DataTables/Plugins#374]
I need to use Datatables Accent neutralise and Diacritics-neutralise-sort plugins together but when I use Diacritics-neutralise-sort the Accent neutralise stop working.

**Comment by DataTables** [comment]
Can you open a [support thread in the forums](//datatables.net/forums) with a link to the page showing the issue please.

**Comment by DataTables** [comment]
I [see you already have a thread](https://datatables.net/forums/discussion/49348/accent-neutralise-and-diacritics-neutralise-sort-work-together?) - closing this as a duplicate.
