### ISSUE TITLE
Locales are still wrong on CDN after pull request.

### ISSUE THREAD

**Issue by Niko9911** [DataTables/Plugins#376]
So, I fixed Finnish localization 3 months ago.
https://github.com/DataTables/Plugins/blob/master/i18n/Finnish.lang

Still when I try use the CDN, there is old and broken version:
https://cdn.datatables.net/plug-ins/1.10.16/i18n/Finnish.json

**Comment by DataTables** [comment]
Yes, I've not yet published an updated version of DataTables, which the plug-ins will be published alongside. 1.10.17 is something I plan to release soon though.

**Comment by Niko9911** [comment]
@DataTables 
Okey, but please note, this update is **critical**!
Finnish translation do not work at all due invalid json before this is patched!

**Comment by DataTables** [comment]
Until then, you could use the file locally rather than loading it from the DataTables CDN.
