### ISSUE TITLE
Extra language translations are not provided for plugins

### ISSUE THREAD

**Issue by expressiveco** [DataTables/Plugins#379]
Extra language translation are not provided for plugins.

I used following to add extra language translations for plugins;
https://gist.github.com/expressiveco/56cb9d0531821d237d78b99efa40a1cb

**Comment by DataTables** [comment]
I'm afraid I don't quite understand what you mean. Do you mean that the translations aren't valid JSON?

**Comment by expressiveco** [comment]
@DataTables datatables.net-plugins\i18n\Turkish.lang does not contain translations for selection.

/*
Extra translations for Turkish i.e. select.
*/
{
  "select": {
    "rows": {
      "_": "%d kayıt seçildi",
      "0": "",
      "1": "1 kayıt seçildi"
    }
  }
}

**Comment by DataTables** [comment]
A pull request with the additional information would be very welcome!

**Comment by DataTables** [comment]
Google translates the text

> Seçmek için bir kayda tıklayın

As:

> Click on a link to select

Is that accurate?

The [English default](https://github.com/DataTables/Select/blob/master/js/dataTables.select.js#L483) is actually to have an empty string there, allowing the user to customise the string if they need to (for a checkbox, link or click on the row). Is that suitable in this case?

**Comment by expressiveco** [comment]
hmm, i think it is better to use "Seçmek için kaydı tıklayın."

I get the English here https://datatables.net/reference/option/language.select.rows.

[German translation](https://github.com/DataTables/Plugins/blob/c4030d991e52991ef47cf822e70f3c9315704b49/i18n/German.lang) is also similar.

**Comment by DataTables** [comment]
I see - thanks. That example is just a demonstration of how the defaults can be changed. The default is not to show anything extra when no items are selected.

Thanks for pointing out that the German file does that - I'll correct that.

**Comment by DataTables** [comment]
Committed into 09119df4af767a6f36b1fa5b512636d85017479f.

Many thanks for your help!

**Comment by expressiveco** [comment]
@DataTables you are welcome. In fact i should thank you for great work.
