### ISSUE TITLE
Polish translation key names

### ISSUE THREAD

**Issue by kolipka** [DataTables/Plugins#387]
Hello,
is there a reason why Polish translation (https://github.com/DataTables/Plugins/blob/master/i18n/Polish.lang) have differend prop names than English?

For datatables translations I use my overall translation mechanism. I have a check to find missing translations that fails because of that.

**Comment by DataTables** [comment]
The English file uses the old Hungarian notation which is backwards compatible. The Polish file uses the new camelCase notation which will work with 1.10 or newer only.
