### ISSUE TITLE
如何自定义列宽

### ISSUE THREAD

**Issue by huanglinjun** [DataTables/Plugins#388]
请问自动缩放列时如何自定义列宽，当列的宽度差超过列宽时自动换行

**Comment by DataTables** [comment]
这不是一个支持论坛。 如果您需要帮助，请在论坛中打开一个新主题，其中包含指向显示问题的测试用例的链接。

This is not a support forum. If you need help, please open a new thread in the forums with a link to a test case showing the issue.
