### ISSUE TITLE
 jQuery is not defined

### ISSUE THREAD

**Issue by yangwei1995** [DataTables/Plugins#402]
I've already quoted  "jquery.js" , but I still can't use plug-ins. 
this is my code:
require('jquery/dist/jquery.js');
require('echarts/map/js/china.js');
require('datatables/media/css/jquery.dataTables.css');
require('datatables/media/js/jquery.dataTables.js');
require('jquery/dist/jquery.min.js');
require('datatables.net-plugins/sorting/ip-address.js');

**Comment by DataTables** [comment]
Hi - could you post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
