### ISSUE TITLE
Incorrect sorting html column type for utf8 (Vietnamese) language

### ISSUE THREAD

**Issue by duongtd96** [DataTables/Plugins#415]
![capture](https://user-images.githubusercontent.com/15135951/50961365-22d0ce80-14fa-11e9-85cd-b00be31b282f.PNG)
As the above picture, when sorting for the second column, datatable handled wrong. In Vietnamese, ``đ`` character is before ``v, x, y`` (it directly after d char). In my case, the second column is html data type, each row is a link, and in picture, it was sorted descending. As you can see, it is incorrect, 3 first rows need to move down to retrieve the correct sorting.

**Comment by DataTables** [comment]
Hi - thanks for this. Are you able to give me a link to a test page showing the issue please? I'm not clear on why using `$().html()` would fix this over `.innerHTML`.

**Comment by duongtd96** [comment]
You can try this: [https://jsfiddle.net/tranduongthdg/304zun1q/3/](url). 
As you can see, column ``name`` working well, but column ``link`` is incorrect.
You can get Vietnamese alphabet: [https://i.ytimg.com/vi/bvaNjHarwDo/maxresdefault.jpg](url)

**Comment by duongtd96** [comment]
Oh, I see, thanks four your response (I don't know why I cannot search this feature :D)
