### ISSUE TITLE
$.fn.dataTable.render.percentBar not working with numbers from ajax

### ISSUE THREAD

**Issue by nikitul** [DataTables/Plugins#429]
The error :

> Object doesn't support property or method 'replace'

 appears at line 74 and just when the data-source is an ajax and the percentage column is a number  (not a string number)

Quick Fix:
```javascript
//change this line (line 74)
s = parseFloat(d.replace(/\s%|%/g,'')).toFixed(vRound);
//to this line
s = parseFloat((d+'').replace(/\s%|%/g,'')).toFixed(vRound);

**Comment by DataTables** [comment]
The version here in git does actually already use `toString`: https://github.com/DataTables/Plugins/blob/master/dataRender/percentageBars.js#L74 . Does that not work for you?

**Comment by nikitul** [comment]
Yep. It works that too.  :)
I've searched on issues for percentBar.js but I didn't checked the source.
I am working with DT 1.10.16.
