### ISSUE TITLE
Lenght i18n

### ISSUE THREAD

**Issue by 8khan** [DataTables/Plugins#433]
Hi, i try to change lenght button caption, following the example showed on [datatables main site](https://datatables.net/examples/basic_init/language.html).

> $(document).ready(function() {
>     $('#example').DataTable( {
>         "language": {
>             "lengthMenu": "Display _MENU_ records per page",
>             "zeroRecords": "Nothing found - sorry",
>             "info": "Showing page _PAGE_ of _PAGES_",
>             "infoEmpty": "No records available",
>             "infoFiltered": "(filtered from _MAX_ total records)"
>         }
>     } );
> } );

but the property of "lengthMenu" dont change the button caption. 

to solve that i follow this [another article](https://datatables.net/forums/discussion/35234/how-do-you-update-the-page-length-button-caption#Comment_93772) that show how to change it manually.

> language: {
>     buttons: {
>         pageLength: '%d'
>     }
> }

**Comment by DataTables** [comment]
It should be `_MENU_` in the `lengthMenu` option. I think that's a Markdown hiccup there!
