### ISSUE TITLE
How to localize strings from DataTables Select plugin? 

### ISSUE THREAD

**Issue by eugene-popov** [DataTables/Plugins#436]
Hello. As we all know it is possible to localize string resources of DataTables lib core. However, I cannot find the way of localizing strings of DataTables Select plugin neither via Ajax request nor by supplying an object with translations directly in the language option of the DataTables initializer.

**Comment by DataTables** [comment]
Hi - could you ask support questions [in the DataTables forums](//datatables.net/forums) please?

The question you pose has already been answer [in the forums](https://www.datatables.net/forums/discussion/55905/).
