### ISSUE TITLE
French Language Not Working

### ISSUE THREAD

**Issue by AniketBhadane** [DataTables/Plugins#437]
I'm using Datatables 1.10.19

I want to localize (internationalize) the table controls.

```
var table = $('#table_id').DataTable({
    language: {
        url: "https://cdn.datatables.net/plug-ins/1.10.19/i18n/French.json"
    }
});
```
The table controls are displayed in English and not French.

When I use ```url: "https://cdn.datatables.net/plug-ins/1.10.19/i18n/German.json"```, the table controls are localized in German language.

Then why is French not working?

**Comment by DataTables** [comment]
There is a bug in the French language file for the current release causing it to be invalid JSON. If you grab the latest file from this repo and host it locally it will work fine.

**Comment by AniketBhadane** [comment]
> There is a bug in the French language file for the current release causing it to be invalid JSON. If you grab the latest file from this repo and host it locally it will work fine.

When is the next release planned?

**Comment by DataTables** [comment]
Probably next month.
