### ISSUE TITLE
i18n - French Language File is malformed

### ISSUE THREAD

**Issue by purplekrayons** [DataTables/Plugins#439]
In the DataTables CDN, the French language file is malformed, which prevents the language from being rendered if used. I did not bother to check if there are other files that are affected.

Referring to this file: https://cdn.datatables.net/plug-ins/1.10.19/i18n/French.json

Note that you must encase the `_`, `0` and `1` in double quotes.

![Screenshot (69)](https://user-images.githubusercontent.com/9218035/57307657-f6e1e600-70b2-11e9-9cdf-f90fbd801b25.png)

Once you encase those keys in double quotes, the language is rendered in the DataTable correctly.

**Comment by DataTables** [comment]
Covered by #437.
