### ISSUE TITLE
dataTables.searchPane.js doesn't appear to support filtering on ampersands (&)

### ISSUE THREAD

**Issue by rdev5** [DataTables/Plugins#442]
Hi,

When using a column to construct a list of filter options using the _searchPane_ plugin, the filter does not appear to match strings containing ampersands in the table properly (returns 0 results).

Replace the ampersand with the word "and" in the table for the plugin is loaded works just fine.

Hopefully this is a minor fix.

Thanks!

**Comment by DataTables** [comment]
Are you able to give me a link to the page showing the issue please? Does that also happen with typing `&` into the global search box for you?

**Comment by colin0117** [comment]
Hi @rdev5 ,

I just fixed [this](https://datatables.net/forums/discussion/53203/searchpane-doesnt-return-results-if-item-contains-an-ampersand#latest) - see this thread here.

Cheers,

Colin

**Comment by rdev5** [comment]
@colin0117 Great, thanks!

@DataTables Sorry, haven't had a chance to get back to you on this. Do we have an idea on any ETA of the next DataTables release and can we confirm that it will include the proposed fix?

**Comment by colin0117** [comment]
Hi again, it'll definitely contain the fix. The next release isn't scheduled yet, but should be in the next month or two at most. C

**Comment by SandyDatatables** [comment]
Coming back to this to say that this was released and resolved in SearchPanes 1.0.0, an example of this working can be found [here](http://live.datatables.net/desoyeyu/1/edit).

Thanks,
Sandy
