### ISSUE TITLE
dataTables.searchPane.js - Sort order does not order same as table

### ISSUE THREAD

**Issue by ghost** [DataTables/Plugins#443]
The sorting of upper case text and lower case text currently pushes all lower cased text after "Z".

Example:
Apple
Ipad
Laptop
Notebook
Zune
ipad
iTunes

Whereas in a table the default sorting would have these ordered A-Z disregarding case.

Looks to be here - l = l.unique().sort().toArray();
But probably needs the same type of base sorting as datatables.js

**Comment by glimpsedchaos** [comment]
Sorry for the "ghost" post. Had a problem with my account and had to recreate.

This issue was posted by me. Just so you know it was not a junk post.

Thanks!

**Comment by DataTables** [comment]
No problem. This is something we are working on (actually, got a solution, but working on related parts before doing a full SearchPane 1.0.0 release).

**Comment by glimpsedchaos** [comment]
Thanks Allan!

**Comment by SandyDatatables** [comment]
Just coming back to this to note that this was released in SearchPanes 1.0.0, you can see the fix [here](http://live.datatables.net/betopaho/2/edit).

Thanks,
Sandy
