### ISSUE TITLE
Ellipses still present on export

### ISSUE THREAD

**Issue by Stephonomon** [DataTables/Plugins#451]
I love the Ellipses.js plugin, however when I'm using it in R and do an export, the shortened cell value remains. It would be nice if that only applied when using the tooltip.

```
datatable(
  react_detail(), 
class = "compact",
  rownames = FALSE,
  filter = "top",
  extensions = c("Buttons", "Select"),
  plugins = "ellipsis",
    options =
    list(
      select = TRUE,
          
      columnDefs = list(list(
      targets = 9,
      render = DT::JS("$.fn.dataTable.render.ellipsis( 10 )"))),
      
      
      searching = TRUE,
      search = list(regex = TRUE, caseInsensitive = TRUE),
      pageLength = 10,
            lengthMenu = c(5, 10, 15, 20, 50, 100, 150, 200, 300),
      scrollX = TRUE,
      scrollY = TRUE,
      dom = "BRSfrtip",
      #order = list(6,"desc"),
      autoWidth = TRUE,
      buttons = list(
        list(
          extend = "copy",
          text = 'Copy All',
          exportOptions = list(modifier = list(selected = FALSE))
        ),
        list(
          extend = "excel",
          text = 'Excel Export',
          exportOptions = list(modifier = list(selected = FALSE))
        ),
        list(
          extend = "print",
          text = 'Print All',
          orientation ='landscape',
          pageSize = 'A4',
          exportOptions = list(modifier = list(selected = FALSE))
        ))
          )
    )

```

**Comment by DataTables** [comment]
Hi,

Could you ask support questions in [the DataTables forums](//datatables.net/forums) in future please? (Looks like you've forgotten to put the template issue text in this repo - sorry).

By default the export will use the `display` data. You can tell it to use something else (e.g. the `filter` might be best here) using the `orthogonal` option as [shown in this example](https://datatables.net/extensions/buttons/examples/html5/outputFormat-orthogonal.html).

**Comment by lenamtl** [comment]
I had several issues with Ellipses long time a go, the case is still opened.
The problem was the span that get duplicated.
https://github.com/DataTables/Plugins/issues/337

What I do is to display only a few characters with ...
I have tried different way like using an hidden column or data-type or tooltip and I got issues with the plugins I'm using.. so I gave up for now...
