### ISSUE TITLE
Release 1.10.20

### ISSUE THREAD

**Issue by sbradish** [DataTables/Plugins#460]
I see that 1.10.20 is tagged of plugins is tagged but not released / available in npm 

![image](https://user-images.githubusercontent.com/30144994/70043136-e564ac00-15b7-11ea-88c2-a0481782841e.png)

- whereas the datatables 1.10.20 is released and available in npm.

![image](https://user-images.githubusercontent.com/30144994/70043115-ded63480-15b7-11ea-8528-eb697f2deb4f.png)

Are there plans to release plugins or is this an oversight?

**Comment by DataTables** [comment]
An oversight! Thanks for letting me know about that. I'll post back shortly when I've published it.

**Comment by DataTables** [comment]
Yup - done now. Thank you again :-).

I'll look into adding this to our scripted releases...
