### ISSUE TITLE
Type based filtering with select element on cell

### ISSUE THREAD

**Issue by lcjury** [DataTables/Plugins#463]
I have a column on my data table which has a select inside. I'm following this example:

https://github.com/DataTables/Plugins/blob/master/filtering/type-based/html.js

But, data tables cache the selects, so, when I change any of them, I'm invalidating the data tables cache, but the search method receives the dom string on the `data` argument, and the dom string doesn't update the selected value.

So, doing something like:

```
var _select = document.createElement('select');
_select.innerHTML = data;
_select.selectedOptions[0].text
```
won't retrieve the selected value but the value which initially has the "selected" attribute. I don't find a way to get around this :(

**Comment by DataTables** [comment]
That is correct - I'm afraid that DataTables currently doesn't handle live DOM elements such as input and select elements very well. You can see that [in this example](https://datatables.net/examples/plug-ins/dom_sort.html). While the sorting works, the filtering does not I'm afraid. Sorry - this is a known limitation at this time.
