### ISSUE TITLE
Is there an option to use ellipsis plugin with dtOptions.columns.push() syntax?

### ISSUE THREAD

**Issue by alekw** [DataTables/Plugins#466]
I am a bit confused how to use ellipsis plugin this way:

`this.dtOptions.columns.push({
        data: 'name', title: 'Name', visible: true, render: (data, type, row) => {
          return row.name;
        }
      });`

Is it at all possible?
This link https://datatables.net/reference/option/columns.render suggests to use substr() directly.

**Comment by DataTables** [comment]
Hi,

Could you post [support questions in the forum please](//datatables.net/forums). That way we have a central, searchable collection of support questions and answers.

What you have above looks like it should work. If it isn't, please link to a test case showing the problem when you post in the forum.

Thanks,
Allan
