### ISSUE TITLE
Error in CDN version of Catalan language plugin

### ISSUE THREAD

**Issue by geraldo** [DataTables/Plugins#474]
[CDN version](https://cdn.datatables.net/plug-ins/1.10.21/i18n/Catalan.json) of the Catalan language plugin has a JSON error. Coma is missing on line 20 and so parsing shows this error:

![Screenshot from 2020-05-21 15-17-23](https://user-images.githubusercontent.com/336371/82562846-56a01780-9b76-11ea-828b-4bafd9000132.png)

[Code in repository](https://github.com/DataTables/Plugins/blob/master/i18n/Catalan.lang) is just fine.

**Comment by DataTables** [comment]
Thank you - it was fixed here: https://github.com/DataTables/Plugins/pull/473.

The 1.10.20 version is valid json: https://cdn.datatables.net/plug-ins/1.10.20/i18n/Catalan.json .

**Comment by geraldo** [comment]
Strange so that a later version (1.10.21) is broken again, or not? Also in 1.10.20 there are missing strings, like loading, etc.

**Comment by DataTables** [comment]
Looks like it was this commit that went wrong: https://github.com/DataTables/Plugins/commit/944abed135ede89df7917e68c3ee34aeae7534c2#diff-668bb669838c987be895c7d71120997e

**Comment by DataTables** [comment]
Are you able to send a PR with corrects?

**Comment by geraldo** [comment]
I could - but I see that it was already done by @raimonesteve Thanks!
