### ISSUE TITLE
novalue custom sort plugin

### ISSUE THREAD

**Issue by dprojects** [DataTables/Plugins#476]
Hi, I made small [novalue.js](https://github.com/dprojects/datatable-sort/blob/master/novalue.js) custom sort plugin. This is similar to [absolute.js](https://github.com/DataTables/Plugins/blob/master/sorting/absolute.js) but differently coded ;-)

Would you like to add it also?
https://github.com/dprojects/datatable-sort/blob/master/novalue.js

**Comment by DataTables** [comment]
Thanks for this! Is there any difference in use over the absolute.js file other than how you tell it which values you want to lock into place (which looks like a global var in this case)?

**Comment by dprojects** [comment]
Hi, thanks for the answer, I've already tested the absolute.js with my project [covid19](https://github.com/dprojects/covid-19) and I found a little difference. 

With absolute.js if you use: 
```
var namesType = $.fn.dataTable.absoluteOrder( [
            { value: '-', position: 'top' }
            ] );
    
    gTable = $('#covid-table').DataTable({
        "orderClasses": true,
        "responsive": true,
        "columnDefs": [ { type: namesType, targets: 7 } ]
    });
```
no matter how many times you click table header you have always "-" at the top. 

In my "plugin" [novalue.js ](https://github.com/dprojects/datatable-sort/blob/master/novalue.js) you can set this string `"-"` to be sorted like e.g. 1000 value or -1000 value, more natutrally. You can achieve the same result with `-pre` just by returning 1000 or -1000 but then you need to know the maximum column value. In my case it is sorted without value limits.

Maybe with absolute.js you can achieve similar result but with novalue you can just use: 
```
gTable.order([4, 'asc'],[2, 'desc']).draw();
```
and is more simple written code. For some people might be useful this way, I guess.

**Comment by DataTables** [comment]
Perfect - thank you. Could you send it as a pull request and we'll pull it in?

**Comment by dprojects** [comment]
I've changed a little bit the description, hope now it is more clear now, if not feel free to change it. 
The pull request is here: https://github.com/DataTables/Plugins/pull/477
