### ISSUE TITLE
[pdfmake] warning failed to load SourceMap

### ISSUE THREAD

**Issue by lenamtl** [DataTables/Plugins#486]
Hi,

I'm testing pdfmake v 0.1.36

I'm getting this warning in Chrome dev tool.

`DevTools failed to load SourceMap: Could not load content for ....pdfmake/pdfmake.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by colin0117** [comment]
also here: https://datatables.net/forums/discussion/63795/pdfmake-warning-failed-to-load-sourcemap#latest

**Comment by lenamtl** [comment]
Hi,

Chrome require the map file so this this file should be included into the package and placed in the same directory of the pdfmake.js

I have downloaded the old version to fit the one used in Datatables package

https://github.com/bpampuch/pdfmake/blob/2edc027eea2ead7e5df6dfd9f264b3b286a03f64/build/pdfmake.min.js.map

That fix the warning issue

**Comment by enigmaelectronica** [comment]
También ha solucionado mi problema gracias 
![PDF MAKE Error](https://user-images.githubusercontent.com/12645694/114470830-c4996700-9bac-11eb-9d8f-43674b7c56a1.png)
