### ISSUE TITLE
Bootstrap 4 Assets are missing on github

### ISSUE THREAD

**Issue by bobonov** [DataTables/Plugins#495]
Bootstrap 4 assets are missing, there is only 1, 2, 3
https://github.com/DataTables/Plugins/tree/master/integration/bootstrap

**Comment by DataTables** [comment]
Our Bootstrap 4 integration is in the [DataTablesSrc repo](/DataTables/DataTablesSrc). The integrations here are legacy and should not be used. Use the [download builder](//datatables.net/download) to get the latest integration files.
