### ISSUE TITLE
Update NPM to 1.10.22

### ISSUE THREAD

**Issue by garretthyder** [DataTables/Plugins#502]
Hello @DataTables I was hoping you could post 1.10.22 to the npm repository here;
https://www.npmjs.com/package/datatables.net-plugins

Mostly hoping to update my app to use the source versions of the conditionalPageLength feature we introduced in #494 and updated in #492

Much appreciated

**Comment by DataTables** [comment]
That's it done now - it will take a new minutes to show up on npmjs.com.

Thanks for the reminder - I'd completely forgotten!

**Comment by garretthyder** [comment]
You rock, thank you so much.
