### ISSUE TITLE
i18n: inconsistent naming of files

### ISSUE THREAD

**Issue by dzhuang** [DataTables/Plugins#535]
The naming of file should follow the same rule, while we can see
1. Both hyphen and underscore were used for lang with region, e.g., `en-gb` , `es_es`
2. Both lowercase and captialization of region were used `es_es`, `bs_BA`.

**Comment by AllanJard** [comment]
Good point - thanks for spotting that. We'll get them updated.

**Comment by SandyDatatables** [comment]
Hi @dzhuang ,

We've fixed this over the following commits:

* https://github.com/DataTables/Plugins/commit/5d683d9770ded30ca221b58a4102e281b689d2dd
* https://github.com/DataTables/Plugins/commit/58122f50f984ae9a9781be9215b6aa056d416738
* https://github.com/DataTables/Plugins/commit/a24a7b847ca896d7a7de06879680740b3db24105

Thanks again for pointing this out to us,
Sandy

**Comment by dzhuang** [comment]
Thanks for the work and promp fix.
