### ISSUE TITLE
Add dataRender/anchor.js to datatables.net

### ISSUE THREAD

**Issue by WinterSilence** [DataTables/Plugins#560]
Please, add `anchor` data render to https://datatables.net/plug-ins/dataRender/

**Comment by AllanJard** [comment]
I think that will happen when I next update the site (which should be tomorrow). I'll leave this issue open until I confirm that.

**Comment by AllanJard** [comment]
Yup, it [is up now](https://datatables.net/plug-ins/dataRender/anchor).
