### ISSUE TITLE
Downstream CVEs due to introduction of prettier-plugin-x

### ISSUE THREAD

**Issue by krsyoung** [DataTables/Plugins#561]
Hello,

It looks like the recent introduction (https://github.com/DataTables/Plugins/commit/87bb97dbb4cc5eef71b58b10be2b41dc029d4e8d from @AllanJard ) of `prettier-plugin-x` dependency has caused a CVE to be added to `datatables.net-plugins` due to downstream dependencies on minimist / minimatch specified in `@prettier-x/formatter-2021-01`.

As soon as I upgrade to `datatables.net-plugins` `1.13.4` I get:

```
d928bba54f14:/app [development] $ yarn audit
yarn audit v1.22.19
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Prototype Pollution in minimist                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.2.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ datatables.net-plugins                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ datatables.net-plugins > prettier-plugin-x > x-formatter >   │
│               │ @prettier-x/formatter-2021-01 > minimist                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091173                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ minimatch ReDoS vulnerability                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.5                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ datatables.net-plugins                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ datatables.net-plugins > prettier-plugin-x > x-formatter >   │
│               │ @prettier-x/formatter-2021-01 > minimatch                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091174                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
2 vulnerabilities found - Packages audited: 471
Severity: 1 High | 1 Critical
``` 

I'm not familiar with the package, but maybe it could be moved to `devDependencies`? 

If it really is an issue, and the package is necessary then the alternative would be that we look to https://www.npmjs.com/package/@prettier-x/formatter-2021-01 for an update of dependencies (although that project does not seem to be particularly active)....

Thoughts?

Thanks!

**Comment by AllanJard** [comment]
Excellent point! Both Prettier X and TypeScript are dev dependencies and not required for actually running the plug-ins. Updated in 41681850e2f870187cab1b106ce02eb8ceb83d6d.

**Comment by krsyoung** [comment]
Big thanks @AllanJard! I pulled from `master` and it works like a charm 👍 

```
# package.json
"datatables.net-plugins": "git+https://github.com/DataTables/Plugins",
```

```
af0ceac800bd:/app [development] $ yarn audit
yarn audit v1.22.19
0 vulnerabilities found - Packages audited: 336
Done in 1.41s.
```

**Comment by maurojs10** [comment]
@AllanJard Sorry to bother, but any plans to release this fix on NPM anytime soon?

**Comment by AllanJard** [comment]
This is thus far the only change in DataTables and the plug-ins since 1.13.4 was released. As far as I am aware, there isn't a way to do a sub-patch release on npm, and since the plug-ins version is matched to the DataTables one, I'm reluctant to make this release until something functional in the code has changed. I don't expect it will be too long - a week or so perhaps.

**Comment by maurojs10** [comment]
Thanks for your quick response.

So I will edit `package-lock.json` to prevent npm from installing the vulnerable packages.

Thank you very much.

**Comment by krsyoung** [comment]
@maurojs10 I went with this approach (if it helps) I put the following in my `package.json` which pins to this fix:

```
"datatables.net-plugins": "git+https://github.com/DataTables/Plugins.git#41681850e2f870187cab1b106ce02eb8ceb83d6d",
```

Thanks again @AllanJard!

**Comment by maurojs10** [comment]
@krsyoung Thanks for that tip.

**Comment by LeoniakM** [comment]
> I don't expect it will be too long - a week or so perhaps.

ok
