### ISSUE TITLE
enum plugin broken since 1.13.5

### ISSUE THREAD

**Issue by eladavron** [DataTables/Plugins#566]
Ever since version `1.13.5` the enum plugin no longer works.
It gives this error message:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'order')
    at e.enum (enum.min.js:2:673)
```

This refers to this bit of code in `enum.js`:
```js
f.type.order[n + "-pre"] = function(e) {
    return t[e]
}
```
Where `f` has no `type` member. This is how `f` looks at this point of the execution:
```json
{
    "detect": [null,null,null,null,null,null,null],
    "search":{},
    "order":{}
}
```

This is as far as I managed to debug it.
Reverting back to `1.13.4` solves the issue for me.

**Comment by AllanJard** [comment]
Gah - sorry! Remove the `.type` from that line and it will work. [Fix committed here](https://github.com/DataTables/Plugins/commit/d2b32a16eb72e67e48adc5780814d29e8fb123bb).
