### ISSUE TITLE
Part 2: utf-8 encoding issue introduced recently

### ISSUE THREAD

**Issue by violuke** [DataTables/Plugins#570]
Following #568, which was very kindly fixed by @AllanJard, we're still having the same problem with some other files.

I've put together what I **think** is a complete list of the problem files.

i18n/zh.js
i18n/sq.js
i18n/pt-PT.js
i18n/ps.js
i18n/ka.js
i18n/mn.js
i18n/te.js
i18n/th.js
i18n/vi.js
i18n/el.js
i18n/pa.js
i18n/bn.js
i18n/sr.js
i18n/hi.js
i18n/ta.js
i18n/sk.js
i18n/uz-CR.js

Would the same fix please be able to be applied to these files? Thank you.

**Comment by AllanJard** [comment]
Thanks! I've done a complete rebuild and I think it is all fixed (along with the latest contributions) here: https://github.com/DataTables/Plugins/commit/afc58016dcef1e65143d7d1da999761feb26787a .

**Comment by violuke** [comment]
Amazing, thanks for the quick response! I'll let you know if we have any other trouble :+1:
