### ISSUE TITLE
Feature searchFade does not work

### ISSUE THREAD

**Issue by interceptor** [DataTables/Plugins#591]
I Assume that all that one has to do is import the Module:

import 'datatables.net-plugins/features/searchFade/dataTables.searchFade.mjs';

then enable the feature when creating the Datatable instance:

searchFade: true

I get the following error:

TypeError: val is undefined
    SearchFade dataTables.searchFade.mjs:45
    
I spent some time trying to understand the code, but am not sure what it is trying to do.

**Comment by AllanJard** [comment]
With DataTables 2 SearchFade is a "feature" which must be placed somewhere around the table with the `layout` option - for example:

```js
var table = new DataTable('#example', {
  layout: {
    topEnd: 'searchFade'
  }
});
```

https://live.datatables.net/cayazesu/1/edit

There it replaces the default `search` feature in the top right, but you could have both if you wanted.
