### ISSUE TITLE
problem with bootstrap_input pagination

### ISSUE THREAD

**Issue by christophe-fms** [DataTables/Plugins#592]
Hello,

I recently migrate from datatable 1.13 to 2.0.8 and i have a problem with the bootstrap_input plugin. I just update the js file and let the config as before (it was working well), but i have no input shown between previous and next link : 
![image](https://github.com/DataTables/Plugins/assets/47887993/78e59d0c-71c6-4fd5-8d93-2777b148c724)
The input seems not to be replaced by the one in the js file. Did i miss something ? The only config done in datatable is this one :  pagingType: 'bootstrap_input'

Best regards

**Comment by AllanJard** [comment]
Switch to [the plugin introduced here](https://datatables.net/blog/2024/inputPaging). The paging plugins were changed in DT2 and the new plugin is a much better way of doing it. The old way no longer works.

**Comment by christophe-fms** [comment]
Thank you, i miss that documentation.
Maybe it is a better way, but it cist more time than just writing pagingType: 'bootstrap_input', it was so simple...
I'll try to do the same

**Comment by ve3** [comment]
The new concept of **features** is good, I've tried to implemented it and it is working good **but** since DataTables v2 still using `dom` (with deprecated notice on the document)... why this plugin just remove the **input**?

![image](https://i.postimg.cc/nLJhWHq6/Screenshot-2025-04-11-at-19-48-39-Data-Tables-v2-plugininput.png)
The input disappeared, left only dots.

Code:
```
new DataTable('#example', {
    'ajax': './data.json',
    'pagingType': 'input',
});
```

**Comment by AllanJard** [comment]
You'll need to update to the rewritten [inputPaging plugin](https://github.com/DataTables/Plugins/tree/master/features/inputPaging) to have it work with `layout`. The old one won't work correctly. [Here is the blog post](https://datatables.net/blog/2024/inputPaging) for the latest version.
