### ISSUE TITLE
Font Awesome and scrollX showing two sets of sorting arrows

### ISSUE THREAD

**Issue by ruhley** [DataTables/Plugins#76]
If you have the font awesome integration css included and have scrollX set to true on the table the sorting arrows are displayed twice. I added the following to the end of the css file to fix it.

div.dataTables_scrollBody table.dataTable thead th.sorting:after,
div.dataTables_scrollBody table.dataTable thead th.sorting_asc:after,
div.dataTables_scrollBody table.dataTable thead th.sorting_desc:after {
    content: "";
}

**Comment by M-Shahbaz** [comment]
Showing me before:

div.dataTables_scrollBody table.dataTable thead th.sorting:before,
div.dataTables_scrollBody table.dataTable thead th.sorting_asc:before,
div.dataTables_scrollBody table.dataTable thead th.sorting_desc:before {
	content: "";
}
