### ISSUE TITLE
Please add releases to the project

### ISSUE THREAD

**Issue by vasa-chi** [DataTables/Plugins#81]
This project is listen in bower packages, but has no releases.

It is possible to put particular commit into bower.json dependencies, but it would be much better and more logical to have release tags.

**Comment by varemenos** [comment]
@DataTables wouldn't it be better if the Plugins repo had the same version number as the DataTables repo's version number to represent which Plugins release is for which DataTables release?

**Comment by DataTables** [comment]
I suppose that is possible, but the plug-in version don't really map 1:1 with DataTables releases. For example the sorting and i18n plug-ins don't relate to DataTables versions at all (beyond their based need for DataTables).

Possibly I should match the main release versions - 1.x.

I'll certainly consider it - thanks for the input.

**Comment by arderyp** [comment]
whatever happened to  datatables-plugins npm package?  Would be a shame to require bower as a dependency just to grab that package there since it isnt in NPM. If I am missing something and it IS in NPM stored under some other name, please let me know.

**Comment by DataTables** [comment]
I've created a `datatables.net-plugins` package on npm: https://www.npmjs.com/package/datatables.net-plugins .

What it is missing is a `main` file since it doesn't really make sense for this kind of repo. You would need to select the file that you want using the require statement.

**Comment by DataTables** [comment]
And now a bower file: https://github.com/DataTables/Plugins/blob/master/bower.json which is published to `datatables.net-plugins` as well.

Its taken an embarrassingly long time for me to do this. I've been wanted to do various other things for the packages, but haven't yet. This is a stop gap.

**Comment by arderyp** [comment]
YESS! that was super quick, thanks so much!
