### ISSUE TITLE
Bootstrap integration layout issues with default dataTables CSS

### ISSUE THREAD

**Issue by snowzach** [DataTables/Plugins#88]
I had a pretty basic standard bootstrap + font-awesome + dataTables page setup and I was having trouble with a little bit of the css. It seems like some of the default dataTables CSS was messing up the layout of the pagination button and was not being properly overridden by the integration css. I was able to fix it by adding this to the css:

/\* Otherwise the search and per page used a bold font set by bootstrap */
.dataTables_length label {
    font-weight: 200;
}

/\* All jacked up by base dataTables CSS, pagination buttons way spread out */
div.dataTables_paginate ul.pagination li.paginate_button {
    margin: 0px;
    padding: 0px;
    border: 0px;
    white-space: nowrap;
}

.dataTables_wrapper .dataTables_paginate .paginate_button:hover {
    border: 0px;
}

.dataTables_wrapper .dataTables_paginate .paginate_button.disabled {
    border: 0px;
}

.dataTables_wrapper .dataTables_paginate .paginate_button.disabled:hover {
    border: 0px;
}

**Comment by sloan58** [comment]
Wow - thanks!  This fixed my pagination layout issue.

**Comment by jaydeluca** [comment]
This just fixed my issue as well, thanks!

**Comment by Gokulbasnett** [comment]
asdasdsad
